version: '3.1'

services:
    mariadb:
        image: 'mariadb:10'
        container_name: zboard-mariadb
        restart: unless-stopped
        environment:
          MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
          MYSQL_ROOT_HOST: "%"
          MYSQL_DATABASE: '${DB_DATABASE}'
          MYSQL_USER: '${DB_USERNAME}'
          MYSQL_PASSWORD: '${DB_PASSWORD}'
          MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        ports:
            - 3306:3306

    apache:
        build:
         context: .
         dockerfile: apache.dockerfile
        container_name: zboard-apache
        restart: unless-stopped
        volumes:
            - ./:/var/www/html/
        ports:
            - 80:80

    phpmyadmin:
        image: phpmyadmin
        container_name: zboard-phpmyadmin
        restart: unless-stopped
        ports:
            - 81:80
        environment:
            - PMA_ARBITRARY=1
            - UPLOAD_LIMIT=300M
